In [1]:
seq=[1,2,3,4,5]
for item in seq:
    print("hi")

hi
hi
hi
hi
hi


In [10]:
seq=[1,2,3,4,5]


In [12]:
for element in seq:
    print (element+element)

2
4
6
8
10


In [13]:
x=[1,2,3,4,5]

In [16]:
out=[]
for num in x:
    out.append(num**2)
print(out)

[1, 4, 9, 16, 25]


In [21]:
[num**2 for num in x]

[1, 4, 9, 16, 25]

In [22]:
[ num**2 for num in x]

[1, 4, 9, 16, 25]

In [23]:
tweet="hello, #style"

In [24]:
tweet.split('#')

['hello, ', 'style']

In [25]:
tweet.split('#') [-1]

'style'

In [1]:
#to remove item from list we use .pop


In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [4]:
import numpy as np

In [4]:
np.arrange(0,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
arr=np.array([[1,2,3],[2,3,4]])

In [9]:
arr

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
#what this linspace function does is it evenly distribute the number between the two numbers

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#np.eye is to get identity matrix

In [19]:
np.random.rand(1)

array([0.77815755])

In [23]:
help(np.random.rand)

NameError: name 'rand' is not defined

In [5]:
np.random.randn(9)

array([ 0.25733715,  2.26648874,  0.29432896, -0.4774208 ,  0.48006109,
       -1.01767197, -0.06241611, -0.54032774,  1.02870117])

In [6]:
import np as numpy

ModuleNotFoundError: No module named 'np'

In [7]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [8]:
import np as numpy

ModuleNotFoundError: No module named 'np'

In [9]:
import numpy as np

In [10]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribu

In [11]:
np.random.seed(50)
np.random.rand(9)

array([0.49460165, 0.2280831 , 0.25547392, 0.39632991, 0.3773151 ,
       0.99657423, 0.4081972 , 0.77189399, 0.76053669])

In [12]:
#this seed function generally use to restrict the change of a random  no like if use only np.random.rand(9)we will get all the time random numbers


In [ ]:
import urllib.request

In [13]:
urllib.request.urlretrieve(https://x.com)

SyntaxError: invalid syntax (586507809.py, line 1)

In [15]:
help(delimiter)

NameError: name 'delimiter' is not defined

In [16]:
help(np.delimiter)

AttributeError: module 'numpy' has no attribute 'delimiter'

In [19]:
myarray = np.array([0,102])

In [18]:
myarray=np.linspace([0,10])

TypeError: linspace() missing 1 required positional argument: 'stop'

In [20]:
myarray = np.array([0,102])

In [21]:
myarray

array([  0, 102])

In [22]:
myarray = np.linspace([0,102])

TypeError: linspace() missing 1 required positional argument: 'stop'

In [23]:
myarray = np.array([0,102])
myarray=np.linspace(0,10)

In [24]:
# TASK: Create a numpy array called myarray which consists of 101 evenly linearly spaced points between 0 and 10.

In [25]:
myarray=np.array([0,102])

In [26]:
myarray

array([  0, 102])

In [27]:
myarray=np.linspace(0,10)

In [28]:
myarray=np.linspace(0,10,101)

In [29]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [ ]:
#indexing ans slicing in numpy

In [35]:
arr=np.arange(0,10)

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [38]:
arr[0:3]

array([0, 1, 2])

In [ ]:
#brodcasting of a array

In [40]:
arr[0:5]=10


In [43]:
arr[0:2]=100

In [45]:
arr_2d=([[2,3,4,5],[12,13,14,15],[11,22,33,44,]])

In [46]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Looking in links: /usr/share/pip-wheels


In [47]:
arr[0:5]=10


In [48]:
arr_2d=([[2,3,4,5],[12,13,14,15],[11,22,33,44,]])

In [49]:
import numpy as np

In [50]:
arr_2d=([[2,3,4,5],[12,13,14,15],[11,22,33,44,]])

In [55]:
arr_2d

[[2, 3, 4, 5], [12, 13, 14, 15], [11, 22, 33, 44]]

In [57]:
arr_2d[1]

[12, 13, 14, 15]

In [60]:
arr_2d[1][2]

14

In [61]:
#conditional selection 

In [64]:
arr_c= np.arange(0,12)

In [65]:
arr_c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
arr_c>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [69]:
bool_arr=arr_c>5

In [70]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [71]:
arr_c[bool_arr]

array([ 6,  7,  8,  9, 10, 11])

In [72]:
#or 

In [73]:
arr_c[arr_c>5]

array([ 6,  7,  8,  9, 10, 11])

In [74]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
dice_rolls[dice_rolls>2]

array([3, 5, 5, 5, 4, 4, 5, 3, 4, 5, 4, 6, 6, 3, 6, 3, 5, 6, 5])

In [75]:
dice_rolls>2

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

In [76]:
len(dice_rolls>2)

29

In [77]:
#to know the standard derivatioon we use arr.std()

In [78]:
arr_c.std()

3.452052529534663

In [88]:
arr_2dd=np.arange(0,25).reshape(5,5)

In [89]:
arr_2dd

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [90]:
arr_2dd.sum()

300

In [91]:
arr_2dd.sum(axis=0)

array([50, 55, 60, 65, 70])

In [92]:
#sum will be pweformed across row

In [ ]:
arr_2dd.sum(axis=1)

In [94]:
import numpy as np
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
account_transactions.sum()

 

2720